export enum PermissionGroupsEnum {
    SANADI_PERMISSIONS_GROUP = 'SANADI_PERMISSIONS_GROUP',
    GENERAL_SERVICES_PERMISSIONS_GROUP = 'GENERAL_SERVICES_PERMISSIONS_GROUP',
    OFFICE_SERVICES_PERMISSIONS_GROUP = 'OFFICE_SERVICES_PERMISSIONS_GROUP',
    PROJECTS_PERMISSION_GROUP = 'PROJECTS_PERMISSION_GROUP',
    ADMIN_PERMISSIONS_GROUP = 'ADMIN_PERMISSIONS_GROUP',
    TRAINING_PROGRAMS_PAGE_GROUP = 'TRAINING_PROGRAMS_PAGE_GROUP',
    TRAINING_PROGRAMS_MENU_ITEM_GROUP = 'TRAINING_PROGRAMS_MENU_ITEM_GROUP',
    COLLECTION_SERVICES_GROUP = 'COLLECTION_SERVICES_GROUP',
    REMITTANCE_PERMISSIONS_GROUP = 'REMITTANCE_PERMISSIONS_GROUP',
    URGENT_INTERVENTION_PERMISSIONS_GROUP = 'URGENT_INTERVENTION_PERMISSIONS_GROUP',
    MANAGE_EXTERNAL_USER_PERMISSIONS_GROUP = 'MANAGE_EXTERNAL_USER_PERMISSIONS_GROUP',
    FOLLOWUP_PERMISSIONS_GROUP = 'FOLLOWUP_PERMISSIONS_GROUP',

    GIVE_USERS_PERMISSIONS = 'GIVE_USERS_PERMISSIONS',

    NEW_PERMISSION_KEY = 'NEW_PERMISSION_VALUE'
}
